EXPERIMENT:
  NAME: ""
  TAG: "FDD,res50,mv1,0.005_2_0.1"
  PROJECT: "imagenet_baselines"
DATASET:
  TYPE: "imagenet"
  NUM_WORKERS: 8
  NUM_CLASSES: 1000
  TEST:
    BATCH_SIZE: 256
DISTILLER:
  TYPE: "FDD"
  TEACHER: "ResNet50"
  STUDENT: "MobileNetV1"
SOLVER:
  BATCH_SIZE: 128
  EPOCHS: 100
  LR: 0.1
  LR_DECAY_STAGES: [30, 60, 90]
  LR_DECAY_RATE: 0.1
  WEIGHT_DECAY: 0.0001
  MOMENTUM: 0.9
  TYPE: "SGD"
FDD:
  LOSS:
    CE_WEIGHT: 1.0
    FEAT_WEIGHT: 0.005
    # 6.0
  EPS: 0.00001
  HINT_LAYER: -1
  LOW_HIGH_RATIO: 2.0
  MASK_RATIO: 0.10
  PROJECTOR: 'bottleneck'
LOG:
  WANDB: False
  TENSORBOARD_FREQ: 10
  SAVE_CHECKPOINT_FREQ: 20
