EXPERIMENT:
  NAME: ""
  TAG: "lbl,res50,mv1"
  PROJECT: "imagenet_baselines"
DATASET:
  TYPE: "imagenet"
  NUM_WORKERS: 8
  NUM_CLASSES: 1000
  TEST:
    BATCH_SIZE: 256
DISTILLER:
  TYPE: "LBL"
  TEACHER: "ResNet50"
  STUDENT: "MobileNetV1"
SOLVER:
  BATCH_SIZE: 128
  EPOCHS: 100
  LR: 0.1
  LR_DECAY_STAGES: [30, 60, 90]
  LR_DECAY_RATE: 0.1
  WEIGHT_DECAY: 0.0001
  MOMENTUM: 0.9
  TYPE: "SGD"
LBL:
  LOSS:
    CE_WEIGHT: 1.0

LOG:
  WANDB: False
  TENSORBOARD_FREQ: 10
  SAVE_CHECKPOINT_FREQ: 20
