EXPERIMENT:
  NAME: ""
  TAG: "FitNet,res34,res18-20"
  PROJECT: "imagenet_baselines"
DATASET:
  TYPE: "imagenet"
  NUM_WORKERS: 8
  NUM_CLASSES: 1000
  TEST:
    BATCH_SIZE: 128
DISTILLER:
  TYPE: "FITNET"
  TEACHER: "ResNet34"
  STUDENT: "ResNet18"
SOLVER:
  BATCH_SIZE: 128
  EPOCHS: 100
  LR: 0.1
  LR_DECAY_STAGES: [30, 60, 90]
  LR_DECAY_RATE: 0.1
  WEIGHT_DECAY: 0.0001
  MOMENTUM: 0.9
  TYPE: "SGD"
FITNET:
  LOSS:
    CE_WEIGHT: 1.0
    FEAT_WEIGHT: 20.0
  HINT_LAYER: 4
LOG:
  WANDB: False
  TENSORBOARD_FREQ: 10
  SAVE_CHECKPOINT_FREQ: 20
